
const TIPS = [
  // Combat (4 tips)
  { cat: 'Combat', tip: 'Archers gain roughly +30% damage and accuracy when positioned on walls or elevated platforms. Build a dedicated archer tower at each corner of your base — 3 tiles high, 2x2 platform, with merlons (wall pieces) for cover. This geometry gives your ranged settlers overlapping fields of fire while keeping them safe from melee attacks.', why: 'Height advantage is a multiplicative combat modifier that turns average archers into killing machines. Every tile of elevation adds ~10% bonus, capping at +30% at 3 tiles above target. Merlons provide 50% cover, reducing incoming ranged damage.' },
  { cat: 'Combat', tip: 'Traps are force multipliers, not primary defenses. Place wooden spike traps in a checkerboard pattern 2 tiles in front of each gate — this forces raiders to path through multiple traps while attacking the gate. Empty spaces between traps prevent raiders from pathing around them. Upgrade to iron traps as soon as smithing is available for triple the damage.', why: 'A single trap deals ~15-20 damage, roughly 1/4 of a raider\'s HP. Five traps in a row can kill a raider before they touch your gate. Checkerboard pattern ensures every path crosses at least 3 traps, bypassing the AI\'s tendency to avoid single obstacles.' },
  { cat: 'Combat', tip: 'Crossbows are for elite marksmen only. A crossbow deals 40-60 damage per shot but has a 3x longer reload time than a bow. Assign crossbows exclusively to settlers with Ranged skill 12+ — below that threshold, the accuracy penalty combined with slow fire rate makes bows strictly superior. One elite crossbowman is worth three novice bowmen.', why: 'Crossbow damage scaling is non-linear. At Ranged 5, a crossbow hits ~30% of shots (effective DPS lower than bow). At Ranged 15, hit rate is ~70% and each shot is devastating. The break-even point is around Ranged 10 — below that, the bow\'s faster fire rate produces more consistent damage output.' },
  { cat: 'Combat', tip: 'During combat, focus fire on one raider at a time rather than spreading damage across multiple enemies. A wounded raider fights at full strength — only death removes the threat. Assign all ranged settlers to target the strongest enemy (plate armor, highest HP) first, then work down. Melee settlers should body-block for archers rather than chasing kills.', why: 'Combat is about removing threats from the field as quickly as possible. Three raiders at 30% HP are exactly as dangerous as three raiders at 100% HP. By eliminating one raider per volley, you reduce enemy DPS output by 33% per kill, creating a cascading advantage.' },
  // Building (4 tips)
  { cat: 'Building', tip: 'Build your base into a hillside, not on flat ground. A hillside location gives you immediate access to underground excavation while maintaining surface access for farming. Excavate rooms at -1F for living quarters (stable temperature, natural insulation) and -2F for food storage (maximum preservation). Surface buildings should be limited to farms, defensive walls, and livestock pens.', why: 'Hillside bases are the most efficient layout because they minimize travel distance between surface (farming) and underground (storage, living). Flat-ground colonies require digging stairs first, then excavating, adding ~10-15 tiles of walking per settler per trip. Over a year, hillside colonies save thousands of settler-walk-tiles in hauling time.' },
  { cat: 'Building', tip: 'Multi-layered walls are exponentially more effective than a single thick wall. A double-layered wall requires raiders to break through two separate barriers — the time this buys you is critical for repositioning defenders and launching counterattacks. A triple-layered wall with a killing zone (empty corridor between layers 2 and 3) filled with traps creates a gauntlet that can annihilate entire raiding parties without settler involvement.', why: 'Raiders prioritize the shortest path to your inner colony. A double wall forces them to break the outer gate, cross the gap, then break the inner gate — buying 2-3x more defense time than a single wall. The killing zone between layers turns passive defense into active damage, with traps dealing ~100+ total damage to a raid before settlers need to engage.' },
  { cat: 'Building', tip: 'Rooms without roofs are useless. Always check that every enclosed space has roof coverage — the roofing tool auto-fills based on wall distance, but irregular shapes can leave gaps. A room with even one missing roof tile counts entirely as "outdoors," negating all room bonuses and exposing settlers to weather. After every construction project, cycle through your rooms and verify roof status.', why: 'The roof mechanic is binary: a room is either fully roofed (indoor) or not (outdoor). A 99% roofed room with one missing tile grants zero mood bonuses, zero temperature insulation, and zero room quality. This is one of the most common beginner mistakes — settlers sleeping in a "room" that the game treats as a field. Always verify with the room inspection tool.' },
  { cat: 'Building', tip: 'Underground temperatures are stable year-round, making underground construction the most reliable way to manage temperature. Living quarters at -1F with a fire source maintain 15-20°C even during winter freezes. Food storage at -2F maintains 2-8°C even during summer heat waves. Surface buildings need extensive heating/cooling to match this — build down, not out, whenever possible.', why: 'Surface temperature fluctuates from -10°C (winter) to 40°C (summer heat wave), a 50°C swing. Underground temperature at -2F stays within a 5-10°C range year-round. This stability is the difference between food lasting 3 days (surface summer) vs 15 days (underground), and settlers freezing (surface winter) vs comfortable (underground with fire).' },
  // Economy (4 tips)
  { cat: 'Economy', tip: 'Beer is the most profitable trade good by a wide margin. Hops cost only growing time (essentially free) and a single brewery produces ~20 units of beer per batch. Beer sells for 40-50 silver per unit and is universally desired by all merchant types. A dedicated brewing operation with 2-3 breweries and a 10x10 hops field can generate 2,000+ silver per year — enough to buy any item merchants offer.', why: 'The profit margin on beer is effectively infinite because hops are a renewable resource with zero ongoing cost beyond settler labor. Compare: iron sword (requires mining ore, smelting ingots, forging — 3 processing steps, non-renewable ore) to beer (plant hops, harvest, brew — 2 steps, renewable). Beer is also weight-efficient for trade: 1 unit of beer = 1 hauling trip for 40-50 silver of value.' },
  { cat: 'Economy', tip: 'Do not hoard silver — spend it on productivity multipliers. A stack of 1,000 silver sitting in a stockpile generates zero value. Spend silver on: medicine kits (prevent settler death), advanced weapons (kill raiders faster), rare seeds (diversify crops), and exotic goods (boost settler mood). Silver you spend on productivity comes back multiplied. Silver you hoard is dead capital.', why: 'The opportunity cost of idle silver is the compound growth you miss. 500 silver spent on a medicine kit that saves your level 15 crafter from infection death is worth more than 10,000 silver — because that crafter produces value every day they are alive. Think of silver as fuel for your colony engine, not a score to maximize.' },
  { cat: 'Economy', tip: 'Process raw materials before selling — always. Raw meat sells for 5-8 silver; smoked meat sells for 15-20 silver. Raw flax sells for 3-5 silver; cloth tunic sells for 20-30 silver. The processing step multiplies value by 2-4x, and the only cost is settler labor time (which is renewable). Never sell raw resources unless you are in a desperate silver emergency — and even then, consider if you can process first.', why: 'Processing is the most reliable value-multiplier in the game. A settler with Cooking 5 can turn 10 raw meat (worth 50-80 silver) into 10 smoked meat (worth 150-200 silver) in roughly 2 in-game hours. That is 70-120 silver of value created per labor-hour. No other economic activity matches this efficiency, and it requires no rare inputs or technology.' },
  { cat: 'Economy', tip: 'Specialized production for trade is more efficient than producing everything yourself. Pick 1-2 trade goods to mass-produce (beer + smoked meat is the optimal early-game combo) and use trade income to buy everything else. A colony trying to produce weapons, armor, medicine, and food in-house will spread its settlers thin and produce everything poorly. A specialized colony produces one thing excellently and trades for the rest.', why: 'Comparative advantage is a real economic principle that applies perfectly to Going Medieval. A brewer-specialized colony can produce 2,000 silver worth of beer with the same labor that a generalist colony would spend producing 800 silver worth of mixed goods. The brewer colony then buys better weapons than the generalist colony could craft, achieving better outcomes in every category through trade.' },
  // Settlers (4 tips)
  { cat: 'Settlers', tip: 'Skill passions (interests) matter more than starting skill levels when recruiting. A settler with Cooking passion at level 3 will reach level 15 faster than a settler without passion at level 8. The 50% XP bonus from passion compounds over time — after 2-3 years, passionate settlers will always surpass non-passionate settlers regardless of starting differences. Always check for passions by observing XP gain rates during the trial period.', why: 'Passion creates a compounding XP advantage. At 150% XP rate, a passionate settler needs 67% of the time to reach each level. Over the 12+ levels needed to reach mastery, this compounds into a roughly 3x speed advantage. A level 3 passionate settler surpasses a level 8 non-passionate settler in approximately 40-50 days of dedicated work — less than one in-game year.' },
  { cat: 'Settlers', tip: 'Dual-specialize every settler into complementary skill pairs. A settler with Mining and Construction becomes a digger-builder — they mine rooms, then build the walls inside them, with zero travel time between jobs. A settler with Farming and Cooking becomes a farmer-chef — they grow food in summer and cook it in winter, staying productive year-round. Avoid single-specialization because it creates idle periods when that one task is not needed.', why: 'Single-specialized settlers spend 30-40% of their time idle or hauling because no single job needs 100% attention. A "Mining only" settler is idle while you plan room layouts, while waiting for other rooms to be cleared, and during winter when outdoor mining is inefficient. Dual-specialization eliminates this dead time. Even a secondary skill at level 5-8 provides meaningful productivity during primary skill downtime.' },
  { cat: 'Settlers', tip: 'Individual bedrooms are the highest-return mood investment in the game. A 4x4 bedroom costs ~20 wood (bed, table, chair, door) and grants +10 permanent mood. Compare this to beer (+8 mood, consumes resources, requires brewing chain) or fine meals (+5 mood, consumes cooking labor). Bedrooms are a one-time cost that pays mood dividends forever. Build them as soon as you have 30+ spare wood after the survival phase.', why: 'Mood is a resource that converts into productivity (happy settlers work faster) and prevents catastrophes (mental breaks cause violence, property destruction, and work stoppages). +10 mood from bedrooms costs ~20 wood once. Producing +10 mood from consumables (beer) costs ongoing settler labor, crop space, and processing time. The return-on-investment for bedrooms is effectively infinite — after roughly 5 days, they have already paid back their construction cost in prevented productivity loss.' },
  { cat: 'Settlers', tip: 'Companion death causes a -20 mood penalty to ALL settlers for several days. This is the single largest mood bomb in the game and can trigger cascading mental breaks that destroy colonies. Protect your settlers at all costs: pull wounded settlers to safety immediately, station medics near combat zones, build hospital beds, and keep medicine stocked. Losing one settler to a raid frequently leads to losing 2-3 more to the resulting mental breaks.', why: 'Death cascades are the #1 cause of colony wipe in mid-game. A settler dies in combat → all settlers get -20 mood → 1-2 settlers drop below 20 mood → mental breaks (violence, wandering, property destruction) → more deaths → more mood penalties → colony collapse. The cascade can kill a 10-settler colony in 3-4 days. Prevention is the only cure — once the cascade starts, it is extremely difficult to stop.' },
  // Farming (4 tips)
  { cat: 'Farming', tip: 'Field size matters enormously. Fields larger than 10x10 will cause harvest delays — a single settler cannot harvest before crops begin rotting in the field. Split large plantings into multiple 8x8 fields instead. This also allows you to rotate crops: one field for cabbage, one for wheat, one for flax, one resting (fallow). Multiple smaller fields also survive blight better — if one field gets infected, the others are physically separated and may be spared.', why: 'Harvest timing is the critical constraint. Crops begin a rot timer roughly 2-3 days after reaching maturity. A 10x10 field takes roughly 8-10 in-game hours for one settler to fully harvest. A 20x20 field takes ~30+ hours — meaning the last tiles will rot before being harvested, wasting roughly 20-30% of the crop. Multiple smaller fields stagger harvest timing, allowing one settler to complete each field before rot starts.' },
  { cat: 'Farming', tip: 'Soil quality directly affects growth speed. Dark brown fertile soil grows crops in roughly 80% of the time of normal soil. Sandy soil (light color) takes roughly 120% of normal time. Always scout for fertile soil patches before placing your first fields — the difference between fertile and sandy soil is roughly a 50% productivity gap per season. In a 15-day growing season, fertile soil can squeeze in one extra harvest cycle compared to sandy soil.', why: 'The 50% productivity gap between fertile and sandy soil compounds over multiple growing seasons. Over 4 harvest cycles per year, fertile soil produces roughly 2 full extra harvests worth of crops compared to sandy soil over 3 years. This is the difference between food abundance and starvation. The 30 seconds you spend scouting for dark soil on Day 1 can save 30 hours of food production scrambling over the next 3 years.' },
  { cat: 'Farming', tip: 'Plant cabbage and wheat in a 1:1 ratio during spring. Cabbage matures in 6 days (fast food), wheat matures in 10 days (processed into bread for winter). The cabbage feeds your colony while waiting for wheat, then wheat becomes the winter staple. After harvesting wheat in summer, immediately replant with more cabbage for a second fast harvest before autumn. This double-cabbage + single-wheat rotation maximizes food output per tile per year.', why: 'Cabbage-wheat rotation is the mathematical optimum for Year 1 food production. One 8x8 cabbage field produces ~50 units in 6 days → feeds 3 settlers for ~8 days. One 8x8 wheat field produces ~35 flour → ~30 bread in 10 days. Total from 16 tiles: ~80 units of food per season. The staggered harvest (cabbage at Day 6, wheat at Day 10) ensures continuous food supply rather than feast-then-famine cycles.' },
  { cat: 'Farming', tip: 'Reserve 10-15% of each harvest as seed stock. Do not eat or process your last seeds. A colony that consumes all its harvested wheat has zero wheat to plant next spring, ending your farming operation. Use stockpile filters to designate a "Seed Reserve" stockpile with highest priority that accepts only seeds. Place this stockpile in a locked room (forbid the door) so settlers cannot accidentally consume it. Unlock only during planting season.', why: 'Seed consumption is a silent colony-killer. There is no alert when your last seed is eaten — you only discover it when you try to plant next spring and find zero seeds available. At that point, you need to buy seeds from a merchant (unreliable) or find wild crop spawns (rare) to restart your farm. A locked seed reserve costs a 2x2 room and takes 5 minutes to set up, preventing a potential colony-ending catastrophe.' },
];

export default function AdvancedTipsPage() {
  return (
    <main className="max-w-6xl mx-auto px-4 lg:px-8 py-8">
      <div className="flex flex-col lg:flex-row gap-12 lg:gap-16">
        <div className="flex-1 lg:max-w-[65%] space-y-10">
          <section>
            <h1 className="chapter-heading">20 Advanced Tips & Tricks</h1>
            <p className="drop-cap font-serif text-base text-ink-light leading-relaxed">
              Beyond the basics of survival and colony management, Going Medieval rewards deep system knowledge with dramatic efficiency gains. These 20 advanced tips cover proven pro-level strategies across Combat, Building, Economy, Settlers, and Farming. Each tip explains not just what to do, but why it works — understanding the underlying mechanics lets you adapt these strategies to your unique colony situation. Master these techniques and you will move from surviving to thriving. Data below is based on community experience and is for reference only.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mb-6">Complete Advanced Tips</h2>
            <div className="grid grid-cols-1 gap-4">
              {TIPS.map((item, i) => (
                <div key={i} className="journal-card p-5">
                  <div className="flex items-center gap-3 mb-3">
                    <span className="font-display text-lg font-bold text-vermillion">{String(i + 1).padStart(2, '0')}</span>
                    <span className="field-tag ink text-[10px]">{item.cat}</span>
                    <span className="font-display text-base font-semibold text-ink flex-1">{item.tip.split('. ')[0].split(': ')[0]}</span>
                  </div>
                  <p className="font-serif text-sm text-ink leading-relaxed mb-3">{item.tip}</p>
                  <div className="aged-border p-3" style={{ backgroundColor: 'var(--color-parchment-deep)' }}>
                    <p className="font-serif text-xs text-ink-light italic">
                      <strong>Why it works:</strong> {item.why}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mb-4">FAQ</h2>
            <div className="faq-item">
              <details>
                <summary>Do these tips work on all difficulty levels?</summary>
                <p>Most tips apply across all difficulties, but higher difficulties require faster execution and more aggressive scaling. On Normal difficulty, you can build a double-layered wall by late Year 1. On Hard, you should have at least the first layer by Day 15 because raids come sooner and hit harder. Core principles (underground storage, specialized settlers, focused-fire combat) are universal — only the urgency changes.</p>
              </details>
            </div>
            <div className="faq-item">
              <details>
                <summary>Which tip gives the biggest immediate improvement?</summary>
                <p>If you implement only one tip today, make it underground food storage (-2F cellar). Temperature-controlled storage extends food shelf life by 3-4x, which cascades into: less food loss, smaller harvest requirements, more settler time for other work, and greater winter safety margin. Every other optimization becomes easier when your food supply is stable and efficient.</p>
              </details>
            </div>
            <div className="faq-item">
              <details>
                <summary>How do I know which optimizations to prioritize?</summary>
                <p>Apply optimizations based on your current colony bottleneck. If food is running out → prioritize farming and storage tips. If raids are killing settlers → prioritize combat and building tips. If silver is scarce → prioritize economy tips. If settlers are unhappy → prioritize settler mood tips. Diagnose the problem first, then apply the relevant solution — do not optimize randomly.</p>
              </details>
            </div>
          </section>
        </div>

        <aside className="lg:w-[35%] space-y-8 shrink-0">
          <div className="field-sidebar-block">
            <h3 className="font-display text-lg font-semibold text-ink mb-4">Tips by Category</h3>
            <div className="flex flex-wrap gap-2">
              {['Combat', 'Building', 'Economy', 'Settlers', 'Farming'].map(cat => (
                <span key={cat} className="field-tag gold text-[10px]">{cat} ({TIPS.filter(t => t.cat === cat).length})</span>
              ))}
            </div>
          </div>
          <div className="journal-card p-5">
            <h3 className="font-display text-base font-semibold text-ink mb-3">Impact Ranking</h3>
            <div className="space-y-2 font-serif text-sm text-ink-light">
              <div className="flex justify-between"><span>Underground storage</span><span className="text-gold">Highest</span></div>
              <div className="flex justify-between"><span>Focus fire combat</span><span className="text-gold">Highest</span></div>
              <div className="flex justify-between"><span>Beer economy</span><span className="text-gold">Highest</span></div>
              <div className="flex justify-between"><span>Hillside base</span><span>High</span></div>
              <div className="flex justify-between"><span>Multi-layered walls</span><span>High</span></div>
              <div className="flex justify-between"><span>Dual specialization</span><span>High</span></div>
            </div>
          </div>
        </aside>
      </div>
    </main>
  );
}
